#!/usr/bin/env python3
"""Build a CSU-formatted Word thesis from the reviewed Markdown manuscript."""

from __future__ import annotations

import copy
import re
import tempfile
from pathlib import Path

import pypandoc
from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.style import WD_STYLE_TYPE
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK, WD_LINE_SPACING
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Pt, RGBColor
from docx.text.paragraph import Paragraph


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "thesis-revision"
OUT = ROOT / "thesis-revision" / "幂型复合条件下鞅Hardy-Orlicz空间对偶性研究_修订稿.docx"

TITLE_CN = "幂型 Young 函数生成的鞅 Hardy–Orlicz 空间的对偶性研究"
TITLE_EN = "Duality of Martingale Hardy–Orlicz Spaces Generated by Power-Type Young Functions"

PAGE_W = 11906  # A4, twentieths of a point
PAGE_H = 16838
MARGIN_TOP = 1417   # 2.5 cm
MARGIN_BOTTOM = 1417
MARGIN_SIDE = 1814  # 3.2 cm, giving a 146 mm text width
HEADER = 850        # 1.5 cm
FOOTER = 992        # 1.75 cm


def read(name: str) -> str:
    return (SRC / name).read_text(encoding="utf-8")


def raw_page_break() -> str:
    return """```{=openxml}
<w:p><w:r><w:br w:type="page"/></w:r></w:p>
```"""


def raw_section_break(*, roman: bool = False) -> str:
    pg_num = '<w:pgNumType w:fmt="lowerRoman" w:start="1"/>' if roman else ""
    return f"""```{{=openxml}}
<w:p><w:pPr><w:sectPr>
<w:type w:val="nextPage"/>
<w:pgSz w:w="{PAGE_W}" w:h="{PAGE_H}"/>
<w:pgMar w:top="{MARGIN_TOP}" w:right="{MARGIN_SIDE}" w:bottom="{MARGIN_BOTTOM}" w:left="{MARGIN_SIDE}" w:header="{HEADER}" w:footer="{FOOTER}" w:gutter="0"/>
{pg_num}
</w:sectPr></w:pPr></w:p>
```"""


def styled(style: str, text: str) -> str:
    return f'::: {{custom-style="{style}"}}\n{text}\n:::'


def split_frontmatter() -> tuple[str, str, str]:
    text = read("00-frontmatter.md")
    cn, rest = text.split("# Abstract", 1)
    en, symbols = rest.split("# 符号说明", 1)
    cn = cn.replace("# 中文摘要", "", 1).strip()
    en = en.strip()
    symbols = symbols.strip()
    return cn, en, symbols


def clean_references() -> str:
    lines = read("references.md").splitlines()
    out: list[str] = ["# 参考文献"]
    for line in lines[1:]:
        if line.startswith("## "):
            if line.startswith("## 六、"):
                break
            continue
        if line.startswith(">"):
            continue
        match = re.match(r"^(\d+)\.\s+(.*)$", line)
        if match:
            out.append(f'[{match.group(1)}] {match.group(2)}')
        else:
            out.append(line)
    return "\n".join(out).strip()


def cover_markdown() -> str:
    cover = [
        styled("CoverTop", "硕士学位论文"),
        styled("CoverTitle", TITLE_CN),
        styled("CoverEnglish", TITLE_EN),
        "",
        styled(
            "CoverInfo",
            "一级学科　数学  \n"
            "二级学科　基础数学  \n"
            "作者姓名　杜闻伦  \n"
            "指导教师　周德俭　副教授  \n\n"
            "中　南　大　学  \n"
            "2027 年 4 月",
        ),
        raw_page_break(),
        styled("TitlePageMeta", "中图分类号　O211.6；O177.2　　　　　　　学校代码　10533  \n"
               "UDC　　　　　　　　　　　　　　　　　学位类别　学术学位"),
        styled("CoverTop", "硕士学位论文"),
        styled("CoverTitle", TITLE_CN),
        styled("CoverEnglish", TITLE_EN),
        styled(
            "CoverInfo",
            "作者姓名　杜闻伦  \n"
            "一级学科　数学  \n"
            "二级学科　基础数学  \n"
            "研究方向　泛函分析与鞅论  \n"
            "二级培养单位　数学与统计学院  \n"
            "指导教师　周德俭　副教授  \n"
            "论文答辩日期　　　　　　　　　答辩委员会主席",
        ),
        styled("CoverInfo", "中　南　大　学  \n2027 年 4 月"),
        raw_page_break(),
        styled("DeclarationTitle", "学位论文原创性声明"),
        "本人郑重声明，所呈交的学位论文是本人在导师指导下进行的研究工作及取得的研究成果。"
        "尽我所知，除了论文中特别加以标注和致谢的地方外，论文中不包含其他人已经发表或撰写过的研究成果，"
        "也不包含为获得中南大学或其他教育机构的学位或证书而使用过的材料。"
        "与我共同工作的同志对本研究所作的贡献均已在论文中作了明确说明。",
        "申请学位论文与资料若有不实之处，本人承担一切相关责任。",
        "学位论文作者签名：　　　　　　　　　日期：　　　年　　月　　日",
        styled("DeclarationTitle", "学位论文版权使用授权书"),
        "本学位论文作者和指导教师完全了解中南大学有关保留、使用学位论文的规定：即学校有权保留并向国家有关部门或机构送交学位论文的复印件和电子版，"
        "允许本学位论文被查阅和借阅。本人授权中南大学可以将本学位论文的全部或部分内容编入有关数据库进行检索和公开传播，"
        "可以采用复印、缩印或其他手段保存和汇编学位论文。",
        "本学位论文属于：□公开　　□延缓公开，延缓期限：　　　年　　月　　日至　　　年　　月　　日",
        "学位论文作者签名：　　　　　　　　　指导教师签名：  \n"
        "日期：　　　年　　月　　日　　　　　日期：　　　年　　月　　日",
        raw_section_break(roman=False),
    ]
    return "\n\n".join(cover)


def manuscript_markdown() -> str:
    cn, en, symbols = split_frontmatter()
    cn_block = "\n\n".join(
        [
            styled("AbstractTitle", TITLE_CN),
            cn.replace(
                "鞅 Hardy–Orlicz 空间",
                "**摘要：**鞅 Hardy–Orlicz 空间",
                1,
            ),
            "图 0 幅，表 2 个，参考文献 23 篇",
            "**关键词：**鞅 Hardy–Orlicz 空间；Young 函数；对偶空间；平方函数；条件平方函数；"
            "\\(K^\\Psi\\) 空间  \n**分类号：**O211.6；O177.2",
        ]
    )
    # Remove duplicated keyword line from the source fragment.
    cn_block = re.sub(r"\n\n\*\*关键词：\*\*.*?(?=\n\n图 0 幅)", "", cn_block, flags=re.S)

    en_block = "\n\n".join(
        [
            styled("AbstractTitle", TITLE_EN),
            en.replace(
                "Martingale Hardy–Orlicz spaces",
                "**Abstract:** Martingale Hardy–Orlicz spaces",
                1,
            ),
            "**Keywords:** martingale Hardy–Orlicz space; Young function; dual space; square function; "
            "conditional square function; \\(K^\\Psi\\) space  \n"
            "**Classification:** O211.6; O177.2",
        ]
    )
    en_block = re.sub(r"\n\n\*\*Keywords:\*\*.*?(?=\n\n\*\*Keywords:\*\*)", "", en_block, flags=re.S)

    body_files = [
        "01-introduction.md",
        "02-preliminaries.md",
        "03-duality.md",
        "04-relations.md",
        "05-conclusion.md",
    ]
    body = "\n\n".join(read(name) for name in body_files)
    endmatter = read("06-achievements-acknowledgments.md")
    parts = [
        cover_markdown(),
        cn_block,
        raw_page_break(),
        en_block,
        raw_page_break(),
        "[[CSU_TOC]]",
        raw_page_break(),
        "# 符号说明\n\n" + symbols,
        raw_section_break(roman=True),
        body,
        clean_references(),
        endmatter,
    ]
    return "\n\n".join(parts)


def set_font(style, *, cn: str, en: str, size: float, bold: bool | None = None) -> None:
    style.font.name = en
    style.font.size = Pt(size)
    if bold is not None:
        style.font.bold = bold
    style.element.rPr.rFonts.set(qn("w:eastAsia"), cn)


def configure_reference_doc(path: Path) -> None:
    doc = Document()
    sec = doc.sections[0]
    sec.page_width = Cm(21)
    sec.page_height = Cm(29.7)
    sec.top_margin = Cm(2.5)
    sec.bottom_margin = Cm(2.5)
    sec.left_margin = Cm(3.2)
    sec.right_margin = Cm(3.2)
    sec.header_distance = Cm(1.5)
    sec.footer_distance = Cm(1.75)

    normal = doc.styles["Normal"]
    set_font(normal, cn="宋体", en="Times New Roman", size=12)
    normal.paragraph_format.line_spacing_rule = WD_LINE_SPACING.EXACTLY
    normal.paragraph_format.line_spacing = Pt(20)
    normal.paragraph_format.first_line_indent = Pt(24)
    normal.paragraph_format.space_after = Pt(0)

    h1 = doc.styles["Heading 1"]
    set_font(h1, cn="黑体", en="Times New Roman", size=16, bold=True)
    h1.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.CENTER
    h1.paragraph_format.space_before = Pt(18)
    h1.paragraph_format.space_after = Pt(12)
    h1.paragraph_format.line_spacing_rule = WD_LINE_SPACING.EXACTLY
    h1.paragraph_format.line_spacing = Pt(20)
    h1.paragraph_format.page_break_before = True

    h2 = doc.styles["Heading 2"]
    set_font(h2, cn="宋体", en="Times New Roman", size=14, bold=True)
    h2.paragraph_format.space_before = Pt(10)
    h2.paragraph_format.space_after = Pt(8)
    h2.paragraph_format.line_spacing_rule = WD_LINE_SPACING.EXACTLY
    h2.paragraph_format.line_spacing = Pt(20)

    h3 = doc.styles["Heading 3"]
    set_font(h3, cn="宋体", en="Times New Roman", size=12, bold=True)
    h3.paragraph_format.space_before = Pt(10)
    h3.paragraph_format.space_after = Pt(8)
    h3.paragraph_format.line_spacing_rule = WD_LINE_SPACING.EXACTLY
    h3.paragraph_format.line_spacing = Pt(20)

    custom = [
        ("CoverTop", "黑体", "Times New Roman", 18, True, WD_ALIGN_PARAGRAPH.CENTER),
        ("CoverTitle", "黑体", "Times New Roman", 22, True, WD_ALIGN_PARAGRAPH.CENTER),
        ("CoverEnglish", "Times New Roman", "Times New Roman", 16, True, WD_ALIGN_PARAGRAPH.CENTER),
        ("CoverInfo", "宋体", "Times New Roman", 16, False, WD_ALIGN_PARAGRAPH.CENTER),
        ("TitlePageMeta", "宋体", "Times New Roman", 12, False, WD_ALIGN_PARAGRAPH.LEFT),
        ("DeclarationTitle", "黑体", "Times New Roman", 16, True, WD_ALIGN_PARAGRAPH.CENTER),
        ("AbstractTitle", "黑体", "Times New Roman", 16, True, WD_ALIGN_PARAGRAPH.CENTER),
        ("TOCHeading", "黑体", "Times New Roman", 16, True, WD_ALIGN_PARAGRAPH.CENTER),
    ]
    for name, cn, en, size, bold, align in custom:
        style = doc.styles.add_style(name, WD_STYLE_TYPE.PARAGRAPH)
        set_font(style, cn=cn, en=en, size=size, bold=bold)
        style.paragraph_format.alignment = align
        style.paragraph_format.line_spacing_rule = WD_LINE_SPACING.EXACTLY
        style.paragraph_format.line_spacing = Pt(20)
        style.paragraph_format.space_before = Pt(12)
        style.paragraph_format.space_after = Pt(12)

    doc.save(path)


def set_repeat_table_header(row) -> None:
    tr_pr = row._tr.get_or_add_trPr()
    tbl_header = OxmlElement("w:tblHeader")
    tbl_header.set(qn("w:val"), "true")
    tr_pr.append(tbl_header)


def set_cell_border(cell, **edges) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    tc_borders = tc_pr.first_child_found_in("w:tcBorders")
    if tc_borders is None:
        tc_borders = OxmlElement("w:tcBorders")
        tc_pr.append(tc_borders)
    for edge in ("top", "bottom", "left", "right", "insideH", "insideV"):
        if edge not in edges:
            continue
        tag = f"w:{edge}"
        element = tc_borders.find(qn(tag))
        if element is None:
            element = OxmlElement(tag)
            tc_borders.append(element)
        for key, value in edges[edge].items():
            element.set(qn(f"w:{key}"), str(value))


def apply_three_line_table(table) -> None:
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = True
    no_line = {"val": "nil"}
    top_bottom = {"val": "single", "sz": "12", "color": "000000"}
    mid = {"val": "single", "sz": "6", "color": "000000"}
    for r_idx, row in enumerate(table.rows):
        for cell in row.cells:
            cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
            edges = {"left": no_line, "right": no_line, "insideV": no_line}
            if r_idx == 0:
                edges.update({"top": top_bottom, "bottom": mid})
            elif r_idx == len(table.rows) - 1:
                edges.update({"bottom": top_bottom})
            set_cell_border(cell, **edges)
            for p in cell.paragraphs:
                p.paragraph_format.first_line_indent = Pt(0)
                p.paragraph_format.line_spacing = 1
                p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                for run in p.runs:
                    run.font.size = Pt(10.5)
                    run.font.name = "Times New Roman"
                    run._element.get_or_add_rPr().rFonts.set(qn("w:eastAsia"), "宋体")
    if table.rows:
        set_repeat_table_header(table.rows[0])


def add_field(paragraph, instruction: str, placeholder: str = "") -> None:
    run = paragraph.add_run()
    fld_char = OxmlElement("w:fldChar")
    fld_char.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = instruction
    separate = OxmlElement("w:fldChar")
    separate.set(qn("w:fldCharType"), "separate")
    text = OxmlElement("w:t")
    text.text = placeholder
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run._r.extend([fld_char, instr, separate, text, end])


def set_page_numbering(section, fmt: str, start: int = 1) -> None:
    sect_pr = section._sectPr
    pg_num = sect_pr.find(qn("w:pgNumType"))
    if pg_num is None:
        pg_num = OxmlElement("w:pgNumType")
        sect_pr.append(pg_num)
    pg_num.set(qn("w:fmt"), fmt)
    pg_num.set(qn("w:start"), str(start))


def add_page_footer(section) -> None:
    section.footer.is_linked_to_previous = False
    paragraph = section.footer.paragraphs[0]
    paragraph.clear()
    paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    add_field(paragraph, "PAGE", "1")
    for run in paragraph.runs:
        run.font.name = "Times New Roman"
        run.font.size = Pt(9)


def add_body_header(section) -> None:
    section.header.is_linked_to_previous = False
    header = section.header
    for paragraph in header.paragraphs:
        paragraph.clear()
    table = header.add_table(rows=1, cols=2, width=Cm(14.6))
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.columns[0].width = Cm(7.3)
    table.columns[1].width = Cm(7.3)
    left = table.cell(0, 0).paragraphs[0]
    left.text = "中南大学硕士学位论文"
    left.alignment = WD_ALIGN_PARAGRAPH.LEFT
    right = table.cell(0, 1).paragraphs[0]
    right.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    add_field(right, 'STYLEREF "Heading 1"', "第1章 绪论")
    for cell in table.rows[0].cells:
        set_cell_border(cell, bottom={"val": "single", "sz": "6", "color": "000000"})
        for p in cell.paragraphs:
            p.paragraph_format.first_line_indent = Pt(0)
            for run in p.runs:
                run.font.name = "Times New Roman"
                run.font.size = Pt(9)
                run._element.get_or_add_rPr().rFonts.set(qn("w:eastAsia"), "宋体")


def replace_toc_marker(doc: Document) -> None:
    for paragraph in doc.paragraphs:
        if paragraph.text.strip() != "[[CSU_TOC]]":
            continue
        paragraph.clear()
        paragraph.text = "目　录"
        paragraph.style = doc.styles["TOCHeading"]
        toc_xml = OxmlElement("w:p")
        paragraph._p.addnext(toc_xml)
        toc_p = Paragraph(toc_xml, paragraph._parent)
        toc_p.paragraph_format.first_line_indent = Pt(0)
        add_field(toc_p, r'TOC \o "1-2" \h \z \u', "打开 Word 后右键更新目录")
        break


def polish_document(doc: Document) -> None:
    # Update fields when Word opens the document.
    settings = doc.settings._element
    update_fields = settings.find(qn("w:updateFields"))
    if update_fields is None:
        update_fields = OxmlElement("w:updateFields")
        settings.append(update_fields)
    update_fields.set(qn("w:val"), "true")

    replace_toc_marker(doc)

    for paragraph in doc.paragraphs:
        fmt = paragraph.paragraph_format
        if paragraph.style.name in {"Normal", "Body Text", "First Paragraph"}:
            fmt.line_spacing_rule = WD_LINE_SPACING.EXACTLY
            fmt.line_spacing = Pt(20)
            fmt.space_after = Pt(0)
            if paragraph.text.strip():
                fmt.first_line_indent = Pt(24)
        if paragraph._p.xpath(".//m:oMath | .//m:oMathPara"):
            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
            fmt.first_line_indent = Pt(0)
        if paragraph.text.startswith("[") and re.match(r"^\[\d+\]", paragraph.text):
            fmt.first_line_indent = Pt(-24)
            fmt.left_indent = Pt(24)
        for run in paragraph.runs:
            run.font.name = "Times New Roman"
            run._element.get_or_add_rPr().rFonts.set(qn("w:eastAsia"), "宋体")

    for table in doc.tables:
        apply_three_line_table(table)

    sections = doc.sections
    if len(sections) < 3:
        raise RuntimeError(f"Expected at least 3 Word sections, found {len(sections)}")

    # Section 0: cover, title page and declarations; no header or page number.
    sections[0].header.is_linked_to_previous = False
    sections[0].footer.is_linked_to_previous = False
    for p in sections[0].header.paragraphs + sections[0].footer.paragraphs:
        p.clear()

    # Section 1: abstracts, TOC and symbols, lower-case Roman page numbers.
    sections[1].header.is_linked_to_previous = False
    for p in sections[1].header.paragraphs:
        p.clear()
    set_page_numbering(sections[1], "lowerRoman", 1)
    add_page_footer(sections[1])

    # Last section: body and all back matter, Arabic page numbers and running header.
    body_section = sections[-1]
    set_page_numbering(body_section, "decimal", 1)
    add_page_footer(body_section)
    add_body_header(body_section)


def build() -> Path:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        reference = tmp_path / "reference.docx"
        source = tmp_path / "thesis.md"
        generated = tmp_path / "generated.docx"
        configure_reference_doc(reference)
        source.write_text(manuscript_markdown(), encoding="utf-8")
        pypandoc.convert_file(
            str(source),
            "docx",
            outputfile=str(generated),
            extra_args=[
                f"--reference-doc={reference}",
                "--from=markdown+raw_attribute+raw_tex+tex_math_single_backslash",
                "--standalone",
            ],
        )
        doc = Document(generated)
        polish_document(doc)
        doc.core_properties.title = TITLE_CN
        doc.core_properties.subject = "中南大学硕士学位论文修订稿"
        doc.core_properties.author = "杜闻伦"
        doc.core_properties.keywords = "鞅 Hardy–Orlicz 空间; Young 函数; 对偶空间"
        doc.save(OUT)
    return OUT


if __name__ == "__main__":
    output = build()
    print(output)
